### ISSUE TITLE
Foto vervangen

### ISSUE THREAD

**Issue by KevindeMeijer** [svIndicium/site#14]
Graag de foto van bestuursjaar 2019-2020 te vervangen voor een van hogere resolutie. Also 2021-2022 komt er aan™️

Deze zijn [hier](https://drive.google.com/drive/folders/1BLKQlZRxVV6ISdW7x90kDg_dVD_64ZN4?usp=share_link ) te vinden.

**Comment by olivierverwoerd** [comment]
tja welke wil je hebben dan. of maak je een pr aan als je hem erin hebt gezet. Beide is prima.
En betreft de foto. We hebben een betere resolutie maar we hebben voor nu even een compressed versie voor alle fotos om de pagina niet zo groot te maken. We moeten nog een keer regelen dat je hem ook in hoge resolutie kan laden.

**Comment by GreenMan36** [comment]
@KevindeMeijer Kan je ons 1 specifieke foto sturen voor op de website?

**Comment by KevindeMeijer** [comment]
![Bestuursfoto-2](https://github.com/svIndicium/site/assets/55430418/c7bcc49a-f46a-4171-bdd8-94de2c03c064)

![Bestuursfoto-1](https://github.com/svIndicium/site/assets/55430418/b1e41b09-05df-43d1-a6d1-8e74717752d4)

In de link die ik hierboven had neergezet waren 2 bestanden met de naam Bestuursfoto te vinden, maar bij deze in de issue. Persoonlijke voorkeur naar het bestand met nummer 2, aka squattend.

**Comment by olivierverwoerd** [comment]
wat is de foto voor 2021-2022

**Comment by KevindeMeijer** [comment]
> wat is de foto voor 2021-2022

Meerdere pogingen voor gedaan, allemaal last minute gecancelled door omstandigheden. Zal voor de zomer dit jaar nog een poging wagen.

**Comment by KevindeMeijer** [comment]
Deze foto staat ondertussen op de website, aldanniet squattend.
