### ISSUE TITLE
/bestuur pagina (2023-2024)

### ISSUE THREAD

**Issue by GreenMan36** [svIndicium/site#20]
De /bestuur pagina is uit de menu.json (verwijderd) en router gehaald (comment) omdat er nog geen foto's waren, die zijn er nu wel.

Er is nog geen groepsfoto dus die hoeft ook niet op de pagina. Maar een foto per bestuurder kan er al wel op. Die vindt je terug in Whatsapp.

**Comment by GreenMan36** [comment]
@dogederp heb jij hulp nodig om de afbeeldingen bij te snijden?

**Comment by dogederp** [comment]
> @dogederp heb jij hulp nodig om de afbeeldingen bij te snijden?

Nee hoor, ik bewerk ze wel zo nodig.
