### ISSUE TITLE
Conscribo documentatie

### ISSUE THREAD

**Issue by GreenMan36** [svIndicium/site#23]
Conscribo api/connector: https://www.conscribo.nl/api/
Documentatie: https://www.conscribo.nl/files/connector/specificatieKoppeling.pdf

Dit is echt kut en cursed, ze hebben maar 1 API endpoint en je moet er commando's in sturen ipv dat ze mooie REST paths hebben.

- [x] Basis in de wiki
- [ ] Laatste token bewaren in Firebase
  - Gebruiker logt in
  - Functie zoekt in firebase of er al nog een werkende token is (Tijd, Token)
  - Als dat niet zo is, loggen we in op Firebase, slaan we de token op en returnen we die
  - Anders hebben we een geldige token en kunnen we een early return doen met de token
- [x] Login endpoints gedocumenteerd in insomnia of postman

**Comment by GreenMan36** [comment]
@olivierverwoerd is het een idee om een mooie postman collectie te maken of te zoeken?

**Comment by GreenMan36** [comment]
Je kan ook maximaal 3 sessies hebben per account dus we moeten wss in de back end "sessions"  bijhouden, inclusief tijd en dan die hergebruiken, ik zou dan 1-3 minuten voordat de ene verloopt, een nieuwe maken en die gebruiken, en dan als de oude sessies zijn verlopen, die token verwijderen uit de database.

Hopelijk kunnen we zo met vele gebruikers alsnog iedereen helpen.

**Comment by siard-y** [comment]
[Wikipagina gemaakt](https://github.com/svIndicium/site/wiki/Conscribo-API) met info en de API basics

**Comment by GreenMan36** [comment]
Voor de DOD zie ik graag Postman of Insomnia

**Comment by GreenMan36** [comment]
Siard gaat eerst kijken naar de endpoint documentatie voor 20 feb

**Comment by siard-y** [comment]
Het is goed. Session bijhouden gaan we niet meer doen. API is wel gedocumenteerd, dus klaar is kees
