### ISSUE TITLE
Conscribo clientside form checks

### ISSUE THREAD

**Issue by siard-y** [svIndicium/site#51]
Het aanmeldformulier is momenteel een iframe en dat werkt best redelijk, maar het liefst willen we client-side checks doen voordat we deze versturen. Dat is niet mogelijk met een iframe. Conscribo heeft ook de mogelijkheid om d.m.v. HTML/CSS/JS het formulier op de website te integreren. Ter referentie:

```html
<link rel="stylesheet" href="https://leden.conscribo.nl/common_resources/css/WebForm.css">
<div id="cwfForm">Formulier wordt geladen ...</div>
<script type="text/javascript" src="https://leden.conscribo.nl/svindicium/jsForm/load/aanmeldenlidmaatschap_kopie/cwfForm"></script> 
```

Het zelf checken van bovenstaand formulier is wel lastig, omdat het wordt gegenereerd uit de JS van Conscribo en die is zacht gezegd nogal matig.

**Comment by siard-y** [comment]
Ik heb het formulier hier https://github.com/svIndicium/site/commit/7b91974290c6bdb47ee8ccf184a3c86ff345a46a geïmplementeerd. Ziet er minder mooi uit dan de iframe, maar dat is wel te fixen.

![Image](https://github.com/svIndicium/site/assets/25852341/1081c9c0-1d9a-4dea-a56b-10d44c124b96)

**Comment by siard-y** [comment]
Deze kan de ijskast uit, aangezien Conscribo weigert de tenaamstelling verplicht te maken, of hier een optie voor te geven.

**Comment by GreenMan36** [comment]
Werkt
