### ISSUE TITLE
VCP pagina

### ISSUE THREAD

**Issue by GreenMan36** [svIndicium/site#54]
We hebben een pagina nodig waar mensen onze vertrouwenscontactpersonen kunnen vinden.

<details><summary>Info voor op de website verkregen van Hanne</summary>
Zit je ergens mee of is er iets vervelends gebeurd? Neem contact op met een van onze vertrouwenscontactpersonen

## Rick 06 23270379 Indicium lid
<img src="https://github.com/svIndicium/site/assets/5887406/0334b0c1-3b98-428e-9128-4337de23e5eb" height=256>  

Over mij: Ik ben 23 jaar, woon in Hilversum en zit in m’n 1e jaar ICT. Hiervoor heb ik twee opleidingen gedaan. Ik verzamel instrumenten en vinyl platen die lastig te krijgen zijn. Ik speel piano en gitaar, ook gek op reizen!

Feitjes over mij:

    Ik heb met de brommer door heel Nederland gereden

    Ik maak oude apparaten modern

    Ik vind warm fruit vies

## Eva 06 11789467 Extern
<img src="https://github.com/svIndicium/site/assets/5887406/5ef1db91-80d4-4e52-90f6-a328692874fd" height=256>  

Over mij: Ik ben 23 jaar, en zit in mijn laatste jaar van de opleiding ambulanceverpleegkundige. Ik woon in Utrecht en werk in Amsterdam maar ik kom oorspronkelijk uit Den Haag. In mijn vrije tijd reis en lees ik veel

Feitjes over mij:

    Ik maak goeie pasta carbonara volgens Hanne

    Ik was bestuur van Cambridgebar

    Ik ben in 30 Europese landen geweest

## Hanne 06 46431597 Indicium bestuur
<img src="https://github.com/svIndicium/site/assets/5887406/e00f0fc6-db7b-4732-8a22-c444050ecc38" height=256>  

Over mij: Ik woon in Vianen, ik ben 20 jaar en ben 4e jaars Open-ICT student. Ik specialiseer me in frontend development. Ik ben bestuur van Indicium en zit bij het kerngroepje van VICT. In mijn vrije tijd lees ik en kook ik veel.

Feitjes over mij:

    Ik stoot me vaak tegen tafels en deuren

    Ik lees boeken in 24 uur uit

    Ik zit op level 4423 van Nonogram
</details>

**Comment by bestuursvindicium** [comment]
@RickMageddon Bumpybump :)

**Comment by siard-y** [comment]
Where code
