### ISSUE TITLE
Home page whitespace

### ISSUE THREAD

**Issue by GreenMan36** [svIndicium/site#74]
> ⚠️ *Lightmode warning* ⚠️

<details><summary>Huidige pagina</summary>

![image](https://github.com/svIndicium/site/assets/5887406/071f92a7-0ee0-4fa9-b89d-320e46bc0a3c)
</details>
Zoals op de afbeelding te zien is, Indicium krijgt steeds meer partners en ook steeds meer activiteiten in de agenda.
Dit neemt vrij veel ruimte op waardoor er witruimte onstaat onderaan de pagina.

Mijn suggestie is als volgd, plaats de partners links en center alles zolang dat past.
<details><summary>Suggestie</summary>

![image](https://github.com/svIndicium/site/assets/5887406/4fb983ec-6219-4309-876a-c1ca3881625d)
</details>

**Comment by siard-y** [comment]
1 april is al voorbij
