### ISSUE TITLE
Documenten beschikbaar maken voor WebKit apparaten (iOS)

### ISSUE THREAD

**Issue by henkdag** [svIndicium/site#81]
Onze statuten en andere documenten zijn voor webkit apparaten niet correct zichtbaar ([een bekend issue met pdf's in iframes](https://stackoverflow.com/questions/75511392/pdf-in-iframe-only-first-page-on-iphone-ipad-view))

Hierom het verzoek om een download link van de statuten aan deze pagina toe te voegen zodat deze op de betreffende apparaten wel beschikbaar is.

**Comment by GreenMan36** [comment]
Ik stel voor om van `userAgentData.ts` gebruik te maken om te kijken of we op webkit zitten en/of mobiel.
En dan automatisch direct door sturen naar het document.

**Comment by GreenMan36** [comment]
Het probleem met PDF dat Henkdag opmerkt is specifiek met bestanden gehost door adobe. [Het probleem ligt tegenwoordig bij safari/webkit op touch devices](https://stackoverflow.com/questions/15480804/problems-displaying-pdf-in-iframe-on-mobile-safari).
Het probleem dat wij meemaken heeft te maken met raar WebKit gedrag.
Ongeveer 17-20% van bezoekers gebruikt safari/webkit dus dit is wel iets wat we moeten onderzoeken, alleen is de oplossing gecompliceerd en onduidelijk.

Het is het beste (naar mijn mening) om gewoon helemaal geen embedded pagina te laten zien op webkit. Of [PDF.js van mozilla](https://mozilla.github.io/pdf.js/).
