### ISSUE TITLE
iOS Aanmeldformulier checkboxes

### ISSUE THREAD

**Issue by siard-y** [svIndicium/site#95]
De checkboxes op het aanmeldformulier op iOS/webkit zijn helemaal afwezig waardoor je geen lid kunt worden

![PXL_20240618_182432269~2.jpg](https://github.com/svIndicium/site/assets/25852341/3bc804ff-63cf-419b-8f68-3c244bf64ce5)

Shoutout naar Tim Apple

**Comment by olivierverwoerd** [comment]
Ik heb even gekeken maar mijn iphone 6 wil zoizo de website niet laden. Dus ik kan hem niet debuggen

**Comment by siard-y** [comment]
Als je deze regel verwijdert wordt het weer zichtbaar op iOS:

![image](https://github.com/svIndicium/site/assets/25852341/3aff25e0-c801-4418-b237-3dfda41a292a)

Tamelijk frappant
